src/Entity/Setting.php
<?php

namespace App\Entity;

use App\Repository\SettingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SettingRepository::class)]
class Setting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $business_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $work_hours = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $instagram_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $facebook_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $youtube_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tiktok_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $business_location = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $twitter_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $linkedin_link = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $google_map_embed = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email_address = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBusinessName(): ?string
    {
        return $this->business_name;
    }

    public function setBusinessName(?string $business_name): static
    {
        $this->business_name = $business_name;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getWorkHours(): ?string
    {
        return $this->work_hours;
    }

    public function setWorkHours(?string $work_hours): static
    {
        $this->work_hours = $work_hours;

        return $this;
    }

    public function getInstagramLink(): ?string
    {
        return $this->instagram_link;
    }

    public function setInstagramLink(?string $instagram_link): static
    {
        $this->instagram_link = $instagram_link;

        return $this;
    }

    public function getFacebookLink(): ?string
    {
        return $this->facebook_link;
    }

    public function setFacebookLink(?string $facebook_link): static
    {
        $this->facebook_link = $facebook_link;

        return $this;
    }

    public function getYoutubeLink(): ?string
    {
        return $this->youtube_link;
    }

    public function setYoutubeLink(?string $youtube_link): static
    {
        $this->youtube_link = $youtube_link;

        return $this;
    }

    public function getTiktokLink(): ?string
    {
        return $this->tiktok_link;
    }

    public function setTiktokLink(?string $tiktok_link): static
    {
        $this->tiktok_link = $tiktok_link;

        return $this;
    }

    public function getBusinessLocation(): ?string
    {
        return $this->business_location;
    }

    public function setBusinessLocation(?string $business_location): static
    {
        $this->business_location = $business_location;

        return $this;
    }

    public function getTwitterLink(): ?string
    {
        return $this->twitter_link;
    }

    public function setTwitterLink(?string $twitter_link): static
    {
        $this->twitter_link = $twitter_link;

        return $this;
    }

    public function getLinkedinLink(): ?string
    {
        return $this->linkedin_link;
    }

    public function setLinkedinLink(?string $linkedin_link): static
    {
        $this->linkedin_link = $linkedin_link;

        return $this;
    }

    public function getGoogleMapEmbed(): ?string
    {
        return $this->google_map_embed;
    }

    public function setGoogleMapEmbed(?string $google_map_embed): static
    {
        $this->google_map_embed = $google_map_embed;

        return $this;
    }

    public function getEmailAddress(): ?string
    {
        return $this->email_address;
    }

    public function setEmailAddress(?string $email_address): static
    {
        $this->email_address = $email_address;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $f_name = null;

    #[ORM\Column(length: 255)]
    private ?string $l_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $residence = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $usertype = null;

    #[ORM\Column(nullable: true)]
    public ?bool $is_active = null;

    /**
     * @var Collection<int, Book>
     */
    #[ORM\OneToMany(targetEntity: Book::class, mappedBy: 'user')]
    private Collection $books;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profile_picture = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $registration_date = null;

    /**
     * @var Collection<int, Presentation>
     */
    #[ORM\OneToMany(targetEntity: Presentation::class, mappedBy: 'user')]
    private Collection $presentations;


    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Cart::class)]
    private Collection $carts;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: OrderItem::class)]
    private Collection $orderItems;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Address::class)]
    private Collection $addresses;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: OrderHistory::class, orphanRemoval: true)]
    private Collection $orderHistories;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Orderr::class)]
    private Collection $orderrs;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Preference::class)]
    private Collection $preferences;

    /**
     * @var Collection<int, County>
     */
    #[ORM\ManyToMany(targetEntity: County::class, inversedBy: 'users')]
    private Collection $county;

    /**
     * @var Collection<int, Constituency>
     */
    #[ORM\ManyToMany(targetEntity: Constituency::class, inversedBy: 'users')]
    private Collection $constituency;

    #[ORM\Column(type: 'boolean')]
    private bool $profileComplete = false;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $about = null;

    /**
     * @var Collection<int, UserRating>
     */
    #[ORM\OneToMany(targetEntity: UserRating::class, mappedBy: 'customer')]
    private Collection $customerRatings;

    /**
     * @var Collection<int, UserRating>
     */
    #[ORM\OneToMany(targetEntity: UserRating::class, mappedBy: 'agent')]
    private Collection $agentRatings;

    /**
     * @var Collection<int, Orderr>
     */
    #[ORM\OneToMany(targetEntity: Orderr::class, mappedBy: 'agent')]
    private Collection $customer_orders;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Blog::class)]
    private Collection $blogs;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->books = new ArrayCollection();
        $this->addresses = new ArrayCollection();
        $this->orderHistories = new ArrayCollection();
        $this->orderrs = new ArrayCollection();
        $this->carts = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
        $this->presentations = new ArrayCollection();
        $this->preferences = new ArrayCollection();
        $this->county = new ArrayCollection();
        $this->constituency = new ArrayCollection();
        $this->customerRatings = new ArrayCollection();
        $this->agentRatings = new ArrayCollection();
        $this->customer_orders = new ArrayCollection();
        $this->blogs = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getFullName();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFName(): ?string
    {
        return $this->f_name;
    }

    public function setFName(string $f_name): static
    {
        $this->f_name = $f_name;

        return $this;
    }

    public function getLName(): ?string
    {
        return $this->l_name;
    }

    public function setLName(string $l_name): static
    {
        $this->l_name = $l_name;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->f_name .' '. $this->l_name;
    }

    public function getAvatarUri(): ?string
    {
        $photoUri = $this->profile_picture;
        if(null == $photoUri){
            return "user.jpg";
        } else {
            return $photoUri;
        }
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getResidence(): ?string
    {
        return $this->residence;
    }

    public function setResidence(?string $residence): static
    {
        $this->residence = $residence;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getUsertype(): ?string
    {
        return $this->usertype;
    }

    public function setUsertype(string $usertype): static
    {
        $this->usertype = $usertype;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): static
    {
        if (!$this->books->contains($book)) {
            $this->books->add($book);
            $book->setUser($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getUser() === $this) {
                $book->setUser(null);
            }
        }

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): static
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registration_date;
    }

    public function setRegistrationDate(?\DateTimeInterface $registration_date): static
    {

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Orderr;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('orderItems', CollectionType::class, [
                'entry_type' => CartItemType::class
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Save Cart'
            ])
            ->add('clear', SubmitType::class, [
                'label' => 'Reset Cart'
            ]);

        $builder->addEventSubscriber(new RemoveCartItemListener());
        $builder->addEventSubscriber(new ClearCartListener());
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Orderr::class,
        ]);
    }
}

templates/cart/order_received.html.twig
{% extends 'base.html.twig' %}
{% block meta_tags %}{{ meta_tags|raw }}{% endblock %}

{% block stylesheets %} 
    <style>

/* Add this CSS to your stylesheet */
.cart-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  max-width:700px;
}

.list-unstyled {
  width: 100%; /* Set the width of the list to 100% */
  padding: 0;
  list-style: none;
}

.cart-item {
  width: 100%; /* Set the width of each cart item to 100% */
  margin-bottom: 20px;
  padding: 15px;
  border: 1px solid #ddd;
  border-radius: 5px;
  font-family: 'Arial', sans-serif;
}

.cart-link {
  color: #333;
  text-decoration: none;
  font-weight: bold;
}

.cart-price,
.cart-total {
  color: #555;
}

.invalid-feedback {
  color: #d9534f;
}

/* Optional: Style for hover effect */
.cart-item:hover {
  background-color: #f9f9f9;
}


        /* Add some basic styling */
        #container {
            position: relative;
        }

        #searchInput {
            width: 100%;
            box-sizing: border-box;
            padding: 5px;
            margin-bottom: 5px;
        }

        #routeSelect {
            width: 100%;
        }

    </style>

{% endblock %}
{% block body %}



    <!-- inner page banner -->
    <div class="dz-bnr-inr overlay-secondary-dark dz-bnr-inr-sm" style="background-image:url({{ asset('site/images/background/bg3.jpg') }});">
        <div class="container">
            <div class="dz-bnr-inr-entry">
                <h1>Order Confirmation</h1>
                <nav aria-label="breadcrumb" class="breadcrumb-row">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ path('app_index') }}"> Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ path('app_shop') }}"> Shop</a></li>
                        <li class="breadcrumb-item">Order Confirmation</li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- inner page banner End-->
    
        <!-- contact area -->
        <section class="content-inner shop-account">
            <!-- Product -->
            <div class="container">
                <div class="dz-divider bg-gray-dark text-gray-dark icon-center  my-5"><i class="fa fa-circle bg-white text-gray-dark"></i></div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="widget">
                            <h4 class="widget-title">Your Order</h4>
                            <table class="table-bordered check-tbl">
                                <thead class="text-center">
                                    <tr>
                                        <th>IMAGE</th>
                                        <th>PRODUCT NAME</th>
                                        <th>TOTAL</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart.orderItems %}
                                    <tr>
                                        <td class="product-item-img"><img src="/site/images/books/{{ item.book.image }}" alt="" width="58" height="132"></td>
                                        <td class="product-item-name">{{ item.book.title }}</td>
                                        <td class="product-price">KSh {{ item.subTotal }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="shop-form widget">
                            <h4 class="widget-title">Order Total</h4>
                            <table class="table-bordered check-tbl mb-4">
                                <tbody>
                                    <tr>
                                        <td>Order Subtotal</td>
                                        <td class="product-price">KSh {{ cart.total }}</td>
                                    </tr>
                                    <tr>
                                        <td>Shipping</td>
                                        <td>
                                            Free Shipping
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Total</td>
                                        <td class="product-price-total">KSh <span id="cartTotal">{{ cart.totalAmount }}</span></td>
                                    </tr>
                                </tbody>
                            </table>
                            <h4 class="widget-title">Payment Method</h4>
                            <p>Mpesa or Cash on Delivery</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Product END -->
        </section>
        <!-- contact area End--> 


{% endblock %}

templates/cart/pay.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title></title>
    <link rel="stylesheet" href="css/main.css" />
    <link rel="icon" href="images/favicon.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
    <style>
        body{
            background-color: #ffffff;

        }
        .container{
            max-width: 600px;
            background-color: #fff;
            padding-top: 100px;
            padding-bottom: 100px;

        }
        .card{
            background-color: #fff;
            width: 300px;
            border-radius: 15px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }
        .name{
            font-size: 15px;
            color: #403f3f;
            font-weight: bold;
        }
        .cross{
            font-size: 11px;
            color: #b0aeb7;
        }
        .pin{
            font-size: 14px;
            color: #b0aeb7;
        }
        .first{
            border-radius: 8px;
            border: 1.5px solid #78b9ff;
            color: #000;
            background-color: #eaf4ff;
        }
        .second{
            border-radius: 8px;
            border: 1px solid #acacb0;
            color: #000;
            background-color: #fff;
        }
        .dot{

        }
        .head{
            color: #137ff3;
            font-size: 12px;
        }
        .dollar{
            font-size: 18px;
            color: #097bf7;
        }
        .amount{
            color: #007bff;
            font-weight: bold;
            font-size: 18px;

        }
        .form-control{
            font-size: 18px;
            font-weight: bold;
            width: 60px;
            height: 28px;

        }
        .back{
            color: #aba4a4;
            font-size: 15px;
            line-height: 73px;
            font-weight: 400;
        }
        .button{
            width: 150px;
            height: 60px;
            border-radius: 8px;
            font-size: 17px;		
        }
        #whatsapp-button {
            position: fixed;
            bottom: 10px;
            left: 10px;
            z-index: 999; /* Adjust the z-index as needed */
            color: white; /* Change the text color */
            padding:5px;
            cursor: pointer;
            /* Add other styles as needed */
        }

    </style>

    </head>

    <body>
    <div class="container d-flex justify-content-center mt-5">
        <div class="card">
            


            <div>
                <div class="d-flex pt-3 pl-3">
                <div><img src="{{ asset('site/images/baby-blossom-logo-text.png') }}" height="60" /></div>
                <div class="mt-3 pl-2"><span class="name">{{app.user.fullName}}</span><div><span class="pin ml-2">{{app.user.phoneNumber}}</span></div></div>
                </div>


                <div class="py-2  px-3">
                    <div class="first pl-2 d-flex py-2">
                    <div class="form-check">
                    <input type="radio" name="optradio" class="form-check-input mt-3 dot" checked>
                    </div>
                    <div class="border-left pl-2"><span class="head">Total amount due</span><div><span class="dollar">KSh </span><span class="amount">{{amountToPay}}</span></div></div>

                    </div>
                </div>


                <div class="py-2  px-3">
                    <div class="second pl-2 d-flex py-2">
                        <div class="border-left pl-2">
                            <span class="head">1. Check your phone ({{app.user.phoneNumber}}).<br/> 2. Input your MPESA pin. <br/>3. Wait for MPESA confirmation message <br/> 4. Click "Complete Order" below</span>
                        </div>

                    </div> 
                </div>	


                    <div class="d-flex justify-content-between px-3 pt-4 pb-3">
                        <div><span class="back">Go back</span></div>
                        <form method="post" action="{{path('checkout_complete_payment')}}">
                            <input type="hidden" name="order_id" id="order_id" value="{{order_id}}" >
                            <input type="hidden" name="request_id" id="request_id" value="{{request_id}}" >     
                            <input type="hidden" name="status" id="status" value="{{status}}" >
                            <input type="hidden" name="amountToPay" value="{{amountToPay}}" >
                            <input type="hidden" name="shipping" value="{{shipping}}" >
                            <button type="submit" class="btn btn-primary button">Complete Order</button>
                        </form>
                    </div>



            </div>
        </div>
        <div id="whatsapp-button"><a href="#"><img src="/whatsapp.png"></a></div>   

    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script>
        const whatsappNumber = "254757066500"; // Replace with your actual number
        const prefilledMessage = "Hi there, I have a question from your website."; // Optional pre-filled message

        const whatsappButton = document.querySelector('#whatsapp-button');

        whatsappButton.addEventListener('click', function() {
        const url = `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(prefilledMessage)}`;
        window.location.href = url;
        });
    </script>

  </body>
</html>

templates/cart/payment_page.html.twig
{{dump(test)}}

templates/cart/status.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title></title>
    <link rel="stylesheet" href="css/main.css" />
    <link rel="icon" href="images/favicon.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
    <style>
        body{
            background-color: #ffffff;

        }
        .container{
            max-width: 600px;
            background-color: #fff;
            padding-top: 100px;
            padding-bottom: 100px;

        }
        .card{
            background-color: #fff;
            width: 300px;
            border-radius: 15px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }
        .name{
            font-size: 15px;
            color: #403f3f;
            font-weight: bold;
        }
        .cross{
            font-size: 11px;
            color: #b0aeb7;
        }
        .pin{
            font-size: 14px;
            color: #b0aeb7;
        }
        .first{
            border-radius: 8px;
            border: 1.5px solid #78b9ff;
            color: #000;
            background-color: #eaf4ff;
        }
        .first-red{
            border-radius: 8px;
            border: 1.5px solid red;
            color: #000;
            background-color: #ffeaea;
        }
        .second{
            border-radius: 8px;
            border: 1px solid #acacb0;
            color: #000;
            background-color: #fff;
        }
        .dot{

        }
        .head{
            color: #137ff3;
            font-size: 12px;
        }
        .dollar{
            font-size: 18px;
            color: #097bf7;
        }
        .amount{
            color: #007bff;
            font-weight: bold;
            font-size: 18px;

        }
        .form-control{
            font-size: 18px;
            font-weight: bold;
            width: 60px;
            height: 28px;

        }
        .back{
            color: #aba4a4;
            font-size: 15px;
            line-height: 73px;
            font-weight: 400;
        }
        .button{
            width: 150px;
            height: 60px;
            border-radius: 8px;
            font-size: 17px;		
        }
        #whatsapp-button {
            position: fixed;
            bottom: 10px;
            left: 10px;
            z-index: 999; /* Adjust the z-index as needed */
            color: white; /* Change the text color */
            padding:5px;
            cursor: pointer;
            /* Add other styles as needed */
        }

    </style>

    </head>

    <body>
    <div class="container d-flex justify-content-center mt-5">
        <div class="card">
            


            <div>
                <div class="d-flex pt-3 pl-3">
                <div><img src="{{ asset('site/images/baby-blossom-logo-text.png') }}" height="60" /></div>
                <div class="mt-3 pl-2"><span class="name">{{app.user.fullName}}</span><div><span class="pin ml-2">{{app.user.phoneNumber}}</span></div></div>
                </div>


                <div class="py-2  px-3">
                    <div class="{{ paymentStatus == 'successful' ? 'first' : 'first-red' }} pl-2 d-flex py-2">
                        <div class="border-left pl-2"><span class="head">Payment</span><div><span class="dollar">{{paymentStatus}} </span></div></div>
                    </div>
                </div>


                <div class="py-2  px-3">
                    <div class="second pl-2 d-flex py-2">
                        <div class="border-left pl-2">
                            {% if paymentStatus == 'successful' %}
                            <span class="head">Your order is complete. Your preferred method of delivery is in process.</span>
                            {% else %}
                            <span class="head">You payment didn't go through. Possible reasons: System problem, Insufficient money. Call +254 757 066500 for assistance</span>
                            {% endif %}
                        </div>

                    </div> 
                </div>	

            </div>
        </div>
        <div id="whatsapp-button"><a href="#"><img src="/whatsapp.png"></a></div>   

    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script>
        const whatsappNumber = "254757066500"; // Replace with your actual number
        const prefilledMessage = "Hi there, I have a question from your website."; // Optional pre-filled message

        const whatsappButton = document.querySelector('#whatsapp-button');

        whatsappButton.addEventListener('click', function() {
        const url = `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(prefilledMessage)}`;
        window.location.href = url;
        });
    </script>

  </body>
</html>