src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $f_name = null;

    #[ORM\Column(length: 255)]
    private ?string $l_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $residence = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $usertype = null;

    #[ORM\Column(nullable: true)]
    public ?bool $is_active = null;

    /**
     * @var Collection<int, Book>
     */
    #[ORM\OneToMany(targetEntity: Book::class, mappedBy: 'user')]
    private Collection $books;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profile_picture = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $registration_date = null;

    /**
     * @var Collection<int, Presentation>
     */
    #[ORM\OneToMany(targetEntity: Presentation::class, mappedBy: 'user')]
    private Collection $presentations;


    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Cart::class)]
    private Collection $carts;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: OrderItem::class)]
    private Collection $orderItems;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Address::class)]
    private Collection $addresses;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: OrderHistory::class, orphanRemoval: true)]
    private Collection $orderHistories;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Orderr::class)]
    private Collection $orderrs;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Preference::class)]
    private Collection $preferences;

    /**
     * @var Collection<int, County>
     */
    #[ORM\ManyToMany(targetEntity: County::class, inversedBy: 'users')]
    private Collection $county;

    /**
     * @var Collection<int, Constituency>
     */
    #[ORM\ManyToMany(targetEntity: Constituency::class, inversedBy: 'users')]
    private Collection $constituency;

    #[ORM\Column(type: 'boolean')]
    private bool $profileComplete = false;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $about = null;

    /**
     * @var Collection<int, UserRating>
     */
    #[ORM\OneToMany(targetEntity: UserRating::class, mappedBy: 'customer')]
    private Collection $customerRatings;

    /**
     * @var Collection<int, UserRating>
     */
    #[ORM\OneToMany(targetEntity: UserRating::class, mappedBy: 'agent')]
    private Collection $agentRatings;

    /**
     * @var Collection<int, Orderr>
     */
    #[ORM\OneToMany(targetEntity: Orderr::class, mappedBy: 'agent')]
    private Collection $customer_orders;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Blog::class)]
    private Collection $blogs;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->books = new ArrayCollection();
        $this->addresses = new ArrayCollection();
        $this->orderHistories = new ArrayCollection();
        $this->orderrs = new ArrayCollection();
        $this->carts = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
        $this->presentations = new ArrayCollection();
        $this->preferences = new ArrayCollection();
        $this->county = new ArrayCollection();
        $this->constituency = new ArrayCollection();
        $this->customerRatings = new ArrayCollection();
        $this->agentRatings = new ArrayCollection();
        $this->customer_orders = new ArrayCollection();
        $this->blogs = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getFullName();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFName(): ?string
    {
        return $this->f_name;
    }

    public function setFName(string $f_name): static
    {
        $this->f_name = $f_name;

        return $this;
    }

    public function getLName(): ?string
    {
        return $this->l_name;
    }

    public function setLName(string $l_name): static
    {
        $this->l_name = $l_name;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->f_name .' '. $this->l_name;
    }

    public function getAvatarUri(): ?string
    {
        $photoUri = $this->profile_picture;
        if(null == $photoUri){
            return "user.jpg";
        } else {
            return $photoUri;
        }
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getResidence(): ?string
    {
        return $this->residence;
    }

    public function setResidence(?string $residence): static
    {
        $this->residence = $residence;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getUsertype(): ?string
    {
        return $this->usertype;
    }

    public function setUsertype(string $usertype): static
    {
        $this->usertype = $usertype;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): static
    {
        if (!$this->books->contains($book)) {
            $this->books->add($book);
            $book->setUser($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getUser() === $this) {
                $book->setUser(null);
            }
        }

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): static
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registration_date;
    }

    public function setRegistrationDate(?\DateTimeInterface $registration_date): static
    {

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/security/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    #[Route(path: '/security/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}

    <!-- inner page banner -->
    <div class="dz-bnr-inr overlay-secondary-dark dz-bnr-inr-sm" style="background-image:url({{ asset('site/images/background/bg3.jpg') }});">
        <div class="container">
            <div class="dz-bnr-inr-entry">
                <h1>Login</h1>
                <nav aria-label="breadcrumb" class="breadcrumb-row">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ path('app_index') }}"> Home</a></li>
                        <li class="breadcrumb-item">Login</li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- inner page banner End-->
    
    <!-- contact area -->
    <section class="content-inner shop-account">
        <!-- Product -->
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 mb-4">
                    <div class="login-area">
                        <div class="tab-content">
                            <h4>{{ render_content('login-register-title', 'NEW CUSTOMER') }}</h4>
                            <p>{{ render_content('login-register-text', 'By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') }}</p>
                            <a class="btn btn-primary btnhover m-r5 button-lg radius-no" href="{{ path('app_register') }}">{{ render_content('login-register-cta', 'CREATE AN ACCOUNT') }}</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 mb-4">
                    <div class="login-area">
                        <div class="tab-content nav">
                        
                            <form id="login" method="post" action="{{ path('app_login') }}" class="tab-pane active col-12">
                                {% if error %}
                                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                                {% endif %}

                                {% if app.user %}
                                    <div class="mb-3">
                                        You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                                        <a class="btn btn-primary btnhover m-r5 button-lg radius-no" href="{{ path('app_logout') }}">Logout</a>
                                        <a class="btn btn-primary btnhover m-r5 button-lg radius-no" href="{{ path('app_index') }}">Homepage</a>
                                    </div>
                                {% else %}                            
                                <h4 class="text-secondary">{{ render_content('login-invite-title', 'LOGIN') }}</h4>
                                <p class="font-weight-600">{{ render_content('login-invite-text', 'If you have an account with us, please log in.') }}</p>
                                <div class="mb-4">
                                    <label class="label-title">E-MAIL *</label>
                                    <input type="email" value="{{ last_username }}" placeholder="Your Email" name="_username" id="username" class="form-control" autocomplete="email" required autofocus>
                                </div>
                                <div class="mb-4">
                                    <label class="label-title">PASSWORD *</label>
                                    <input placeholder="Type Password" type="password" name="_password" id="password" class="form-control" autocomplete="current-password" required>
                                </div>
                                <input type="hidden" name="_csrf_token"
                                    value="{{ csrf_token('authenticate') }}"
                                >
                                <input type="hidden" name="_target_path" value="/checkout">
                                <div class="checkbox mb-3">
                                    <input type="checkbox" name="_remember_me" id="_remember_me">
                                    <label for="_remember_me">Remember me</label>
                                </div>
                                <div class="text-left">
                                    <button class="btn btn-primary btnhover me-2" type="submit">login</button>
                                    <a href="{{ path('app_forgot_password_request')}}" class="m-l5"><i class="fas fa-unlock-alt"></i> Forgot Password</a> 
                                </div>

                                {% endif %}
                            </form>
                            {% if app.user %}
                            {% else %}
                            
                                {# {{ render(controller('App\\Controller\\ResetPasswordController::renderForgotPasswordForm')) }} #}
                                
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Product END -->
    </section>
    <!-- contact area End--> 

{% endblock %}