src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PageRepository::class)]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $page_content = null;

    #[ORM\Column(nullable: true)]
    private ?bool $content_first = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_service = null;

    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'pages')]
    private Collection $sections;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function __construct()
    {
        $this->sections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getPageContent(): ?string
    {
        return $this->page_content;
    }

    public function setPageContent(?string $page_content): static
    {
        $this->page_content = $page_content;

        return $this;
    }

    public function isContentFirst(): ?bool
    {
        return $this->content_first;
    }

    public function setContentFirst(?bool $content_first): static
    {
        $this->content_first = $content_first;

        return $this;
    }

    public function isIsService(): ?bool
    {
        return $this->is_service;
    }

    public function setIsService(?bool $is_service): static
    {
        $this->is_service = $is_service;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }
}

src/Entity/SEO.php
<?php

namespace App\Entity;

use App\Repository\SEORepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SEORepository::class)]
class SEO
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_path = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $keywords = null;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logo_path;
    }

    public function setLogoPath(?string $logo_path): static
    {
        $this->logo_path = $logo_path;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): static
    {
        $this->keywords = $keywords;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $f_name = null;

    #[ORM\Column(length: 255)]
    private ?string $l_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $residence = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $usertype = null;

    #[ORM\Column(nullable: true)]
    public ?bool $is_active = null;

    /**
     * @var Collection<int, Book>
     */
    #[ORM\OneToMany(targetEntity: Book::class, mappedBy: 'user')]
    private Collection $books;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profile_picture = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $registration_date = null;

    /**
     * @var Collection<int, Presentation>
     */
    #[ORM\OneToMany(targetEntity: Presentation::class, mappedBy: 'user')]
    private Collection $presentations;


    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Cart::class)]
    private Collection $carts;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: OrderItem::class)]
    private Collection $orderItems;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Address::class)]
    private Collection $addresses;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: OrderHistory::class, orphanRemoval: true)]
    private Collection $orderHistories;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Orderr::class)]
    private Collection $orderrs;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Preference::class)]
    private Collection $preferences;

    /**
     * @var Collection<int, County>
     */
    #[ORM\ManyToMany(targetEntity: County::class, inversedBy: 'users')]
    private Collection $county;

    /**
     * @var Collection<int, Constituency>
     */
    #[ORM\ManyToMany(targetEntity: Constituency::class, inversedBy: 'users')]
    private Collection $constituency;

    #[ORM\Column(type: 'boolean')]
    private bool $profileComplete = false;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $about = null;

    /**
     * @var Collection<int, UserRating>
     */
    #[ORM\OneToMany(targetEntity: UserRating::class, mappedBy: 'customer')]
    private Collection $customerRatings;

    /**
     * @var Collection<int, UserRating>
     */
    #[ORM\OneToMany(targetEntity: UserRating::class, mappedBy: 'agent')]
    private Collection $agentRatings;

    /**
     * @var Collection<int, Orderr>
     */
    #[ORM\OneToMany(targetEntity: Orderr::class, mappedBy: 'agent')]
    private Collection $customer_orders;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Blog::class)]
    private Collection $blogs;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->books = new ArrayCollection();
        $this->addresses = new ArrayCollection();
        $this->orderHistories = new ArrayCollection();
        $this->orderrs = new ArrayCollection();
        $this->carts = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
        $this->presentations = new ArrayCollection();
        $this->preferences = new ArrayCollection();
        $this->county = new ArrayCollection();
        $this->constituency = new ArrayCollection();
        $this->customerRatings = new ArrayCollection();
        $this->agentRatings = new ArrayCollection();
        $this->customer_orders = new ArrayCollection();
        $this->blogs = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getFullName();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFName(): ?string
    {
        return $this->f_name;
    }

    public function setFName(string $f_name): static
    {
        $this->f_name = $f_name;

        return $this;
    }

    public function getLName(): ?string
    {
        return $this->l_name;
    }

    public function setLName(string $l_name): static
    {
        $this->l_name = $l_name;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->f_name .' '. $this->l_name;
    }

    public function getAvatarUri(): ?string
    {
        $photoUri = $this->profile_picture;
        if(null == $photoUri){
            return "user.jpg";
        } else {
            return $photoUri;
        }
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getResidence(): ?string
    {
        return $this->residence;
    }

    public function setResidence(?string $residence): static
    {
        $this->residence = $residence;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getUsertype(): ?string
    {
        return $this->usertype;
    }

    public function setUsertype(string $usertype): static
    {
        $this->usertype = $usertype;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): static
    {
        if (!$this->books->contains($book)) {
            $this->books->add($book);
            $book->setUser($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getUser() === $this) {
                $book->setUser(null);
            }
        }

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): static
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registration_date;
    }

    public function setRegistrationDate(?\DateTimeInterface $registration_date): static
    {

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	{% if page.sections | default([]) | length > 0 %}

		{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}

		{% for section in sortedSections %}	
		{{ include('sections/' ~ section.templatePath) }}
		{% endfor %}

	{% endif %}

{% endblock %}

templates/index/page.html.twig
{% extends 'base.html.twig' %}
{% block meta_description %}{{page.metaDescription}}{% endblock %}
{% block meta_title %}{{page.metaTitle }}{% endblock %}
{% block body %}

	{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}
    {% if page.pageContent|length > 1 %}
        {% include('sections/variable_banner.html.twig') %}
        {% if page.contentFirst %}
            {% include ('sections/service.html.twig') %}
            {% for section in sortedSections %}	
            {{ include('sections/' ~ section.templatePath) }}
            {% endfor %}
        {% else %}
            {% for section in sortedSections %}	
            {{ include('sections/' ~ section.templatePath) }}
            {% endfor %}
            {% include ('sections/service.html.twig') %}
        {% endif %}
    {% else %}
        {% for section in sortedSections %}
            {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}    
    {% endif %}

{% endblock %}

templates/index/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Profile | Home Health Education Service{% endblock %}

    {% block body %}
        <!-- Content -->
        <div class="page-content bg-white">
            <!-- contact area -->
            <div class="content-block">
                <!-- Browse Jobs -->
                <section class="content-inner bg-white">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-3 col-lg-4 m-b30">
                                <div class="sticky-top">
                                    <div class="shop-account">
                                        <div class="account-detail text-center">
                                            <div class="my-image">
                                                <a href="javascript:void(0);">
                                                    {% set profPic = app.user.profilePicture == "" ? 'user.jpg' : app.user.profilePicture %}
                                                    <img alt="{{ user.fName }}" src="{{ asset('site/images/profile_pictures/' ~ profPic ) }}">
                                                </a>
                                            </div>
                                            <div class="account-title">
                                                <div class="">
                                                    <h4 class="m-b5"><a href="javascript:void(0);">{{ user.fullname }}</a></h4>
                                                    <p class="m-b0"><a href="javascript:void(0);">{{ user.usertype|title }}</a></p>
                                                </div>
                                                {% if app.user.category == 'le' %}
                                                <!-- Agent URL Display and Copy Button -->
                                                <div class="agent-url mt-3">
                                                    <input type="text" id="agentUrl" class="form-control" value="{{ app.request.scheme ~ '://' ~ app.request.host ~ path('set_agent', {'username': user.username}) }}" readonly>
                                                    <button class="btn btn-primary mt-2" onclick="copyAgentUrl()">Copy URL</button>
                                                </div>
                                                {% endif %}
                                                <!-- End of Agent URL Display and Copy Button -->
                                            </div>
                                        </div>
                                        <ul>
                                            <li>
                                                <a href="#" class="active"><i class="far fa-user" aria-hidden="true"></i> 
                                                <span>Profile</span></a>
                                            </li>
                                            <li>
                                                <a href="{{ path('cart') }}"><i class="flaticon-shopping-cart-1"></i>
                                                <span>My Cart</span></a>
                                            </li>
                                            <li>
                                                <a href="{{ path('app_shop') }}"><i class="fa fa-briefcase" aria-hidden="true"></i> 
                                                <span>Shop</span></a>
                                            </li>
                                            <li>
                                                <a href="#faq"><i class="far fa-id-card" aria-hidden="true"></i> 
                                                <span>FAQ</span></a>
                                            </li>
                                            <li>
                                                <a href="#privacy_policy"><i class="fa fa-key" aria-hidden="true"></i> 
                                                <span>Privacy Policy</span></a>
                                            </li>
                                            <li>
                                                <a href="{{ path('app_logout') }}"><i class="fas fa-sign-out-alt" aria-hidden="true"></i> 
                                                <span>Log Out</span></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-9 col-lg-8 m-b30">
                                <div class="shop-bx shop-profile">
                                    <div class="shop-bx-title clearfix">
                                        <h5 class="text-uppercase">Basic Information</h5>
                                    </div>
                                    {{ form_start(form) }}
                                        <div class="row m-b30">
                                            <div class="col-lg-6 col-md-6">
                                                <div class="mb-3">
                                                    {{ form_label(form.f_name) }}
                                                    {{ form_widget(form.f_name, {'attr': {'class': 'form-control'}}) }}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="mb-3">
                                                    {{ form_label(form.l_name) }}
                                                    {{ form_widget(form.l_name, {'attr': {'class': 'form-control'}}) }}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="mb-3">
                                                    {{ form_label(form.username) }}
                                                    {{ form_widget(form.username, {'attr': {'class': 'form-control'}}) }}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="mb-3">
                                                    {{ form_label(form.residence) }}
                                                    {{ form_widget(form.residence, {'attr': {'class': 'form-control'}}) }}
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12">
                                                <div class="mb-3">
                                                    {{ form_label(form.about) }}
                                                    {{ form_widget(form.about, {'attr': {'class': 'form-control'}}) }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="shop-bx-title clearfix">
                                            <h5 class="text-uppercase">Contact Information</h5>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                <div class="mb-3">
                                                    {{ form_label(form.phone) }}
                                                    {{ form_widget(form.phone, {'attr': {'class': 'form-control'}}) }}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="mb-3">
                                                    {{ form_label(form.email) }}
                                                    {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="mb-3">
                                                    {{ form_label(form.county) }}
                                                    <div class="form-control overflow-auto" style="height: 200px;">
                                                        {% for child in form.county %}
                                                            <div class="form-check">
                                                                {{ form_widget(child, {'attr': {'class': 'form-check-input'}}) }}
                                                                {{ form_label(child, null, {'label_attr': {'class': 'form-check-label'}}) }}
                                                            </div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="mb-3">
                                                    {{ form_label(form.constituency) }}
                                                    <div class="form-control overflow-auto" style="height: 200px;">
                                                        {% for child in form.constituency %}
                                                            <div class="form-check">
                                                                {{ form_widget(child, {'attr': {'class': 'form-check-input'}}) }}
                                                                {{ form_label(child, null, {'label_attr': {'class': 'form-check-label'}}) }}
                                                            </div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <button class="btn btn-primary btnhover">Save Setting</button>
                                    {{ form_end(form) }}
                                </div>    
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Browse Jobs END -->
            </div>
        </div>
        <!-- Content END-->
    {% endblock %}

{% block javascripts_bottom %}

    <script>

    const constituencies = {
        {% for county, constituencies in countyData %}
            "{{ county }}": [
                {% for constituency in constituencies %}
                    "{{ constituency }}"{% if not loop.last %},{% endif %}
                {% endfor %}
            ]{% if not loop.last %},{% endif %}
        {% endfor %}
    };

    function loadConstituencies() {
        const selectedCounty = $("#countySelect").val();
        const $constituencySelect = $("#constituencySelect");

        // Clear the constituency dropdown
        $constituencySelect.html('<option value="">--Select Constituency--</option>');

        if (selectedCounty && constituencies[selectedCounty]) {
            $.each(constituencies[selectedCounty], function(index, constituency) {
                $constituencySelect.append($('<option></option>').val(constituency).text(constituency));
            });
        }

        // Refresh the Bootstrap Select dropdown
        $constituencySelect.selectpicker('refresh');
    }

    $(document).ready(function() {
        console.log("jQuery Loaded");
        // Populate the countySelect dropdown
        const $countySelect = $("#countySelect");
        $.each(constituencies, function(county) {
            $countySelect.append($('<option></option>').val(county).text(county));
        });

        // Refresh the Bootstrap Select dropdown
        $countySelect.selectpicker('refresh');

        // Add change event listener to countySelect using on()
        $("#countySelect").on('change', loadConstituencies);
    });

    // Function to copy agent URL to clipboard
    function copyAgentUrl() {
        const agentUrl = document.getElementById("agentUrl");
        agentUrl.select();
        agentUrl.setSelectionRange(0, 99999); // For mobile devices

        navigator.clipboard.writeText(agentUrl.value).then(function() {
            alert("URL copied to clipboard!");
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }
    </script>

{% endblock %}

templates/index/service.html.twig
{% extends 'base.html.twig' %}
{% block meta_description %}{{page.metaDescription}}{% endblock %}
{% block meta_title %}{{page.metaTitle }}{% endblock %}
{% block body %}

	{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}
    {% include('sections/service_banner.html.twig') %}
    {% if page.contentFirst %}
        {% include ('sections/service.html.twig') %}
        {% for section in sortedSections %}	
        {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}
    {% else %}
        {% for section in sortedSections %}	
        {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}
        {% include ('sections/service.html.twig') %}
    {% endif %}

{% endblock %}

templates/index/test2.html.twig
{{dump(statements)}}